Improve workflow error handling and add npm registry access
Added registry.npmjs.org to allowed outbound hosts in all workflows and included a step to checkout the Central Tooling Repo. Enhanced error handling for 'aws cloudformation deploy' commands by redirecting output to a log file and surfacing errors in main.yml and onboard-environment.yml.

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -48,6 +48,10 @@ jobs:
             s3.amazonaws.com:443
             s3.ap-southeast-1.amazonaws.com:443
             s3.us-east-1.amazonaws.com:443
+            registry.npmjs.org:443
+
+      - name: Checkout Central Tooling Repo
+        uses: actions/checkout@v4
 
       - name: Checkout Application Repository
         uses: actions/checkout@v4
@@ -133,4 +137,10 @@ jobs:
             --stack-name ${{ env.STACK_NAME }} \
             --parameter-overrides ${{ steps.load_config.outputs.overrides_string }} LambdaCodeS3Bucket=${{ env.S3_BUCKET }} LambdaCodeS3Key=${{ env.S3_KEY }} \
             --capabilities CAPABILITY_NAMED_IAM \
-            --no-fail-on-empty-changeset > /dev/null
+            --no-fail-on-empty-changeset > deployment_output.log 2>&1
+            
+          if [ $? -ne 0 ]; then
+            echo "::error::'aws cloudformation deploy' command failed. See error output below:"
+            cat deployment_output.log
+            exit 1
+          fi
diff --git a/.github/workflows/onboard-environment.yml b/.github/workflows/onboard-environment.yml
--- a/.github/workflows/onboard-environment.yml
+++ b/.github/workflows/onboard-environment.yml
@@ -52,6 +52,7 @@ jobs:
             ssm.us-east-1.amazonaws.com:443
             cloudformation.ap-southeast-1.amazonaws.com:443
             cloudformation.us-east-1.amazonaws.com:443
+            registry.npmjs.org:443
 
       - name: Checkout Central Tooling Repo
         uses: actions/checkout@v4
@@ -102,12 +103,21 @@ jobs:
           echo "::add-mask::$STACK_NAME"
           echo "::add-mask::$TOOLING_ROLE_ARN"
           echo "Deploying client stack..."
+
+          # Redirect output to a log file and check for errors
           aws cloudformation deploy \
             --template-file client.yaml \
             --stack-name "$STACK_NAME" \
             --parameter-overrides ToolingRoleArn=$TOOLING_ROLE_ARN \
             --capabilities CAPABILITY_NAMED_IAM \
-            --no-fail-on-empty-changeset > /dev/null
+            --no-fail-on-empty-changeset > deployment_output.log 2>&1
+
+          if [ $? -ne 0 ]; then
+            echo "::error::'aws cloudformation deploy' command failed. See error output below:"
+            cat deployment_output.log
+            exit 1
+          fi
+
           echo "stack_name=$STACK_NAME" >> $GITHUB_ENV
 
       - name: Get Deployment Role ARN
